services:
  - type: web
    name: panda-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000